```plantuml
!global $ARCH_LOCAL = %true()
!$LOCAL_FOLDER = "https://github.com/plantuml-stdlib/Archimate-PlantUML/blob/master/dist/plantuml-stdlib/stdlib/archimate/Archimate.puml"
!include $LOCAL_FOLDER/Archimate.puml
```


```plantuml
Category_ElementName(nameOfTheElement, "description", $nest=%false(), $special=$ARCH_SPECIAL_SHAPES)
```
